### ISSUE TITLE
Please add access to random numbers to gen3 templates

### ISSUE THREAD

**Issue by ml019** [codeontap/gen3-freemarker-wrapper#1]
Please make random numbers available to gen3 templates. Suggest the approach described here - https://sourceforge.net/p/freemarker/discussion/2346/thread/f053d79c/

**Comment by kshychko** [comment]
@ml019, does the change works for you? shall we close the issue?

**Comment by ml019** [comment]
Havn't tested it yet. Will leave open for now

**Comment by ml019** [comment]
Would you please

1. update the dist directory with the latest version (I realise not practice to have code in the repo but I think it is justified in this case)
2. Correct the display of the version - it is showing v.null.

**Comment by kshychko** [comment]
The latest 1.3 version has been added to the dist directory.
Display of the version works normally for me:

```
D:\work\codeontap\gen3-freemarker-wrapper\freemarker-wrapper\dist>java -jar freemarker-wrapper-1.3.jar -?

GSGEN v.1.3

Freemarker version - 2.3.25
Params:
-i  : template file.
-v  : variables for freemarker template.
-r  : raw variables for freemarker template.
-o  : output file.
-d  : templates directory.
-?  or --version                 : Display this help.

```

**Comment by ml019** [comment]
Closing as functionality now inproduction
