### ISSUE TITLE
<fix> Only attempt to JSON parse files ending in .json

### ISSUE THREAD

**Issue by ml019** [codeontap/gen3-freemarker-wrapper#14]
At present, parse exceptions are being thrown if a file is not in JSON format eg. pem files.

Need to 
- check the lower cased extension is "json" before attempting to parse the file
- include the full physical file path when logging a JSON file parse exception

**Comment by kshychko** [comment]
fixed in v1.9.21

**Comment by ml019** [comment]
@kshychko I'm no longer getter the parse exceptions. Think we can close this one.

**Comment by roleyfoley** [comment]
When parsing JSON files into freemarker can we also freemarker null support 

- When a key has a null value - remove the key and value
- if an array has a null value - remove the null value from the array 

In JQ we do the following 
https://github.com/codeontap/gen3/blob/b0553d7bd53a56f87059178614756401b9d0561e/execution/nullStrip.jq

**Comment by ml019** [comment]
@roleyfoley It is already there
