### ISSUE TITLE
<refactor> getCMDBs should return a freemarker object

### ISSUE THREAD

**Issue by ml019** [codeontap/gen3-freemarker-wrapper#15]
Currently this function returns a string. It should return a freemarker compatible array. If not already implemented, the "ActiveOnly" option flag should also be implemented.

**Comment by kshychko** [comment]
refactored in v1.9.21
`ActiveOnly` is enabled by default. Way to disable:

```
getCMDBs(
    {
	"ActiveOnly" : false
    }
  )
```

**Comment by ml019** [comment]
@kshychko If no ActiveOnly flag is provided, all repos are shown rather than just the active ones.

**Comment by kshychko** [comment]
ActiveOnly originally implemented disabled, sorry for confusion.
