### ISSUE TITLE
IP Address Conversion Support

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3-freemarker-wrapper#2]
Some AWS resources, WAF only support specific CIDR masks: 

> AWS WAF supports /8, /16, /24, and /32 IPv4 address ranges and /16, /24, /32, /48, /56, /64, and /128 IPv6 address ranges. For more information about CIDR notation, see the Wikipedia entry Classless Inter-Domain Routing.

Most other resources support standard CIDR masking (i.e. any mask). Instead of restricting the codeontap configuration to only support the WAF masks we would like to have a function which can convert a given CIDR mask into an array of /32 IP addresses. WAF supports 10,000 IP Addresses in a single rule so it shouldn't be an issue to expand most subnets.

**Comment by roleyfoley** [comment]
Freemarker doesn't support this so we need to fall back to a Java based function. 
I came across this library https://seancfoley.github.io/IPAddress/ which seems to cover off the scenarios we need.

**Comment by roleyfoley** [comment]
a basic implementation of this functionality would be 
```
IPAddress subnet = new IPAddressString("192.168.0.0/28").getAddress();
       IPAddress newSubnets = subnet.setPrefixLength(32, false);
       TreeSet<IPAddress> subnetSet = new TreeSet<IPAddress>();
       Iterator<? extends IPAddress> iterator = newSubnets.prefixBlockIterator();
       while (iterator.hasNext()) {
           subnetSet.add(iterator.next());
       }
       System.out.println(subnetSet);
```
Which essentially is given a subnet provide all of the /32 subnets within it. The freemarker function should accept two parameters, a network and a prefix iteration length. 

This would allow flexibility in iterating through large address blocks, e.g. instead of splitting a /16 network into /32 subnets it could be split into /24 subnets.

**Comment by roleyfoley** [comment]
@kshychko Could you have a look at integrating this into the current freemarker wrapper?

**Comment by kshychko** [comment]
@roleyfoley shall we close this issue?
